#!/usr/bin/env node
// Genera src/version.ts senza incrementare la versione (usato per preprod)

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '../package.json');
const versionFilePath = path.join(__dirname, '../src/version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const currentVersion = packageJson.version;

const timestamp = new Date().toISOString();
const buildNumber = Date.now();

const versionContent = `// Auto-generated by scripts/generate-version.js
// DO NOT EDIT MANUALLY

export const VERSION = {
  version: '${currentVersion}',
  buildNumber: ${buildNumber},
  buildDate: '${timestamp}',
};
`;

fs.writeFileSync(versionFilePath, versionContent);
console.log(`✅ Version file generated: ${currentVersion}`);
