#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Percorsi
const packageJsonPath = path.join(__dirname, '../package.json');
const versionFilePath = path.join(__dirname, '../src/version.ts');
const envProdPath = path.join(__dirname, '../src/environments/environment.prod.ts');
const envDevPath = path.join(__dirname, '../src/environments/environment.ts');

// Leggi package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const currentVersion = packageJson.version;

// Incrementa la versione (patch)
const versionParts = currentVersion.split('.').map(Number);
versionParts[2]++; // Incrementa patch
const newVersion = versionParts.join('.');

// Aggiorna package.json
packageJson.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');

// Crea/aggiorna version.ts
const timestamp = new Date().toISOString();
const buildNumber = Date.now();
const versionContent = `// Auto-generated by scripts/increment-version.js
// DO NOT EDIT MANUALLY

export const VERSION = {
  version: '${newVersion}',
  buildNumber: ${buildNumber},
  buildDate: '${timestamp}',
};
`;

fs.writeFileSync(versionFilePath, versionContent);

// Aggiorna environment.prod.ts
updateEnvironmentFile(envProdPath, newVersion);

// Aggiorna environment.ts (opzionale, per dev)
updateEnvironmentFile(envDevPath, newVersion);

console.log(`✅ Version incremented: ${currentVersion} → ${newVersion}`);
console.log(`📦 Build number: ${buildNumber}`);
console.log(`📅 Build date: ${timestamp}`);

// Funzione helper per aggiornare i file environment
function updateEnvironmentFile(filePath, version) {
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  File not found: ${filePath}`);
    return;
  }
  
  let content = fs.readFileSync(filePath, 'utf8');
  content = content.replace(/version:\s*['"][\d.]+['"]/, `version: '${version}'`);
  fs.writeFileSync(filePath, content);
  console.log(`✅ Updated: ${path.basename(filePath)}`);
}
